### ISSUE TITLE
Request.withCredentials is not set to true

### ISSUE THREAD

**Issue by MazeChaZer** [simonh1000/elm-jwt#12]
```elm
{-| createRequest creates a Http.Request with the token added to the headers, and
sets the `withCredentials` field to True.
-}
createRequest : String -> String -> String -> Http.Body -> Json.Decoder a -> Request a
createRequest method token url body dec =
    request
        { method = method
        , headers =
            [ header "Authorization" ("Bearer " ++ token) ]
        , url = url
        , body = body
        , expect = expectJson dec
        , timeout = Nothing
        , withCredentials = False
        }
```

The comment seems to contradict the source code.

**Comment by simonh1000** [comment]
Fixed in 5.0.0

**Comment by fdbeirao** [comment]
This is an old and closed issue, but I have stumbled across the same discrepancy.

[Human readable documentation says `withCredentials` is set to `True`](https://github.com/simonh1000/elm-jwt/blob/5.3.0/src/Jwt.elm#L217), but [source code says otherwise](https://github.com/simonh1000/elm-jwt/blob/5.3.0/src/Jwt.elm#L247). If there is a particular reason for this discrepancy, it would be cool to mention it in the human readable documentation.

PS: I just stumbled on this, I am not using this particular function.

Kudos!

**Comment by simonh1000** [comment]
good catch - thanks for that

**Comment by simonh1000** [comment]
I've fixed this in master, and that'll get wound into the next release
